[dependencies]

[package]
  cjc-version = "0.55.3"
  compile-option = "-Woff unused"
  description = "Dependency injection implementation of Cangjie. Inspired by Microsoft.Extensions.DependencyInjection."
  link-option = ""
  name = "dependency_injection"
  output-type = "dynamic"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
